# 工作流的名称
name: Build and Release EXE

# 触发工作流的事件
on:
  push:
    tags:
      - 'QQ-Group-Images Cleaner-v*' # <--- 已更新！匹配新的标签格式

# 工作流中运行的任务 (jobs)
jobs:
  build-windows:
    # 指定运行此任务的虚拟机环境
    runs-on: windows-latest

    # 关键修复1：为任务授予创建Release的权限
    permissions:
      contents: write # <--- 新增！这是解决403权限错误的关键

    # 任务的步骤
    steps:
      # 第一步：检出 (Checkout) 代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 第三步：安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 第四步：使用 PyInstaller 打包
      - name: Build executable with PyInstaller
        run: >
          pyinstaller
          --noconfirm
          --onefile
          --windowed
          --name "QQ-Group-Images-Cleaner"
          --version-file version.txt
          qq_group_images_cleaner.py
      
      # 第五步：创建 Release 并上传打包好的文件
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          # files: 指定要上传的文件路径
          files: dist/QQ-Group-Images-Cleaner.exe